server:
  port: 8080
spring:
  application:
    name: InstanceService
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${REGISTRY_IP:localhost}:${REGISTRY_PORT:8761}/eureka


KubeSphereConfig:
  url: ${KUBESPHERE_URL:http://192.168.1.104:30880}
  username: ${KUBESPHERE_USERANME:admin}
  password: ${KUBESPHERE_PASSWORD:Admin000123}