server:
  port: 8080
spring:
  application:
    name: InstanceService

KubeSphereConfig:
  url: ${KUBESPHERE_URL:http://192.168.1.104:30880}
  username: ${KUBESPHERE_USERANME:admin}
  password: ${KUBESPHERE_PASSWORD:Admin000123}